### ISSUE TITLE
Problem installing on Remnux

### ISSUE THREAD

**Issue by kamiloxf** [wahlflo/eml_analyzer#16]
Hello,
I ran the Remnux distribution on a virtual machine (Ubuntu-based distribution for Malware analysis)
The problem is that during installation I get this error: https://pastebin.com/raw/RigS9EuA 

I have tried the following installation methods:
- Installation with pip install
- compiling from code using git clone and make

Please help me install

**Comment by wahlflo** [comment]
Hi @kamiloxf,
I'm afraid this this error is caused by your pip3 setup and not by the ``eml-analyzer`` package. At least error line ``FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'`` incidates that. 
I would suggest to try using a virtual environment: https://docs.python.org/3/library/venv.html  and then trying to install it within the virtual env.

Also, please check if you get the same error when you try to install other packages
