### ISSUE TITLE
eml_analyzer --text throws cyrillic characters instead of german umlauts

### ISSUE THREAD

**Issue by mrchang0815** [wahlflo/eml_analyzer#17]
Hi,

I face a issue when parsing outgoing mails:

Extract from the eml-File (save-as via Thunderbird):
"...
This is a cryptographically signed message in MIME format.

--------------ms090908070501060903060609
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 8bit

ä

..."

If the plain text contains i. e. a "ä" the output character becomes cyrillic "д" independend from the chosen output format "--text" or "--text --format json".

In comparison an extract from a eml-File that get's parsed correctly:

"...
--eTqZtiOboXMORarM2jeks2PNUJpOw=_O7X
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
...
"

Any idea?

I add a test-file.

Regards,
MrChang.
[test.zip](https://github.com/wahlflo/eml_analyzer/files/12162193/test.zip)

**Comment by wahlflo** [comment]
Hi, 
I can confirm the bug on Linux, on Windows it works fine. Looks like the return value of the method ``Message.get_payload`` from the python library is based on the OS.

Input ``Dies ist ein dämlicher Test.``  
Output on Windows: ``b'Dies ist ein d\xc3\xa4mlicher Test.'``
Output on Linux: ``b'Dies ist ein d\xe4mlicher Test.'``

I added a unit test to test this behaviour on Ubuntu and Windows: https://github.com/wahlflo/eml_analyzer/pull/18  
To find and fix the root cause one needs to analyze the ``Message.get_payload`` method from the python library.

**Comment by wahlflo** [comment]
So @mrchang0815,

The difference between Windows and Linux was caused since the default encoding when the file is read is different. I set it now explicit to utf-8. 

I had a look at email library, it looks like that the value ``8bit`` of the ``Content-Transfer-Encoding:`` is not considered.

I will create an issue for the standard library. For the meantime I implemented a fix in the ``eml-analyzer``
